apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
        system:masters
      rolearn: arn:aws:iam::343090658568:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-23T20:15:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1004"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b71f98b9-0c84-43a4-afc5-b87881c3d831
